shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ProductList.as_view()),
    path('<int:pk>/', views.ProductDetail.as_view()),
    path('<int:pk>/new_comment/', views.new_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('delete_comment/<int:pk>', views.delete_comment),
    path('update_product/<int:pk>/', views.ProductUpdate.as_view()),
    path('create_product/', views.ProductCreate.as_view()),
    path('category/<str:slug>/', views.category_page),
    path('manufacturer/<str:slug>/', views.manufacturer_page),
    path('tag/<str:slug>/', views.tag_page),
    path('search/<str:q>/', views.ProductSearch.as_view())
]

shoppingmall/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('', include('single_pages.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop/models.py
from allauth.socialaccount.templatetags import socialaccount
from django.db import models
from django.contrib.auth.models import User
import os

# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/shop/tag/{self.slug}/'

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/shop/category/{self.slug}/'

    class Meta:
        verbose_name_plural = 'Categories'

class Manufacturer(models.Model):
    #서버 이름
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    nickname = models.CharField(max_length=100) # 아이템 소유자 아이디
    phone_num = models.CharField(max_length=100) # 연락처
    addr = models.CharField(max_length=100) # 마을

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/shop/manufacturer/{self.slug}/'

    class Meta:
        verbose_name_plural = 'Manufacturers'

class Product(models.Model):
    name = models.CharField(max_length=50)
    hook_text = models.CharField(max_length=100, blank=True)

    head_image = models.ImageField(upload_to='shop/images/%Y/%m/%d/', blank=True)
    # %Y 2022, %y 22

    content = models.TextField(blank=True)

    price = models.IntegerField(default=1)
    scissors = models.IntegerField(default=10)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    #다대일 관계
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)

    manufacturer = models.ForeignKey(Manufacturer, null=True, blank=True, on_delete=models.SET_NULL)

    #다대다 관계
    tags = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return f'[{self.pk}]{self.name}::{self.author} : {self.created_at}'

    def get_absolute_url(self):
        return f'/shop/{self.pk}/'

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return 'https://dummyimage.com/50x50/ced4da/6c757d.jpg'


class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.author} : {self.content}'

    def get_absolute_url(self):
        return f'{self.product.get_absolute_url()}#comment-{self.pk}'

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return 'https://dummyimage.com/50x50/ced4da/6c757d.jpg'

shop/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta: #특정한 변수의 값을 바꾸기 위해, 미리 지정해둔 예약어를 바꾸기 위해 값을 지정해줄 수 있음
        model = Comment
        fields = ('content',)

shop/views.py
from django.shortcuts import render, redirect
from .models import Product, Category, Tag, Comment, Manufacturer
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.utils.text import slugify
from .forms import CommentForm
from django.shortcuts import get_object_or_404
from django.db.models import Q

# Create your views here.
def delete_comment(request, pk):
    comment =  get_object_or_404(Comment, pk=pk)
    product = comment.product
    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        return redirect(product.get_absolute_url())
    else:
        PermissionDenied

class ProductUpdate(LoginRequiredMixin, UpdateView):
    model = Product
    fields = ['name', 'hook_text', 'head_image', 'content', 'price', 'scissors', 'category', 'manufacturer']
    template_name = 'shop/product_update_form.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(ProductUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def form_valid(self, form):
        response = super(ProductUpdate, self).form_valid(form)
        self.object.tags.clear()
        tags_str = self.request.POST.get('tags_str')
        if tags_str:
            tags_str = tags_str.strip()  # 앞 뒤에 빈 공간 없애주는 명령
            tags_str = tags_str.replace(',', ';')
            tag_list = tags_str.split(';')
            for t in tag_list:
                t = t.strip()
                tag, is_tag_created = Tag.objects.get_or_create(name=t)
                if is_tag_created:
                    tag.slug = slugify(t, allow_unicode=True)
                    tag.save()
                self.object.tags.add(tag)
        return response

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductUpdate,self).get_context_data()
        if self.object.tags.exists:
            tag_str_list = list()
            for t in self.object.tags.all():
                tag_str_list.append(t.name)
            context['tags_str_default'] = ';'.join(tag_str_list)
        context['categories'] = Category.objects.all()
        context['no_category_product_count'] = Product.objects.filter(category=None).count
        return context

class ProductCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Product
    fields = ['name', 'hook_text', 'head_image', 'content', 'price', 'scissors', 'category', 'manufacturer']
    #모델면_form.html

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_superuser or current_user.is_staff):
            form.instance.author = current_user
            response = super(ProductCreate, self).form_valid(form)
            tags_str = self.request.POST.get('tags_str')
            if tags_str:
                tags_str = tags_str.strip() #앞 뒤에 빈 공간 없애주는 명령
                tags_str = tags_str.replace(',', ';')
                tag_list = tags_str.split(';')
                for t in tag_list:
                    t = t.strip()
                    tag, is_tag_created = Tag.objects.get_or_create(name=t)
                    if is_tag_created:
                        tag.slug = slugify(t, allow_unicode=True)
                        tag.save()
                    self.object.tags.add(tag)
            return response
        else:
            return redirect('/shop/')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductCreate,self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_product_count'] = Product.objects.filter(category=None).count
        return context

class ProductList(ListView):
    model = Product
    #ordering = '-pk'
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductList,self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_product_count'] = Product.objects.filter(category=None).count
        return context


class ProductSearch(ProductList):  # ListView 상속, 모델명_list 형태로 데이터 전달, 템플릿도 모델명_list.html
    paginate_by = 5

    def get_queryset(self):
        q = self.kwargs['q']
        product_list = Product.objects.filter(Q(name__contains=q)).distinct()
        return product_list

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search: {q} ({self.get_queryset().count()})'
        return context

class ProductDetail(DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context = super(ProductDetail, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_product_count'] = Product.objects.filter(category=None).count
        context['comment_form'] = CommentForm
        return context

def new_comment(request, pk):
    if request.user.is_authenticated:
        product = get_object_or_404(Product, pk=pk)
        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.product = product
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url()) #클라이언트에 서버가 할 일을 마지고 보내주는 정보
        else: #Get
            return redirect(product.get_absolute_url())
    else: #로그인 안 한 사용자
        raise PermissionDenied

class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


def category_page(request, slug):
    if slug == 'no_category':
        category = "미분류"
        product_list = Product.objects.filter(category=None)
    else:
        category = Category.objects.get(slug=slug)
        product_list = Product.objects.filter(category=category)
    return render(request, 'shop/product_list.html', {
        'category' : category,
        'product_list' : product_list,
        'categories' : Category.objects.all(),
        'no_category_product_count' : Product.objects.filter(category=None).count
    })

def manufacturer_page(request, slug):
    if slug == 'no_manufacturer':
        manufacturer = "미분류"
        product_list = Product.objects.filter(manufacturer=None)
    else:
        manufacturer = Manufacturer.objects.get(slug=slug)
        product_list = Product.objects.filter(manufacturer=manufacturer)
    return render(request, 'shop/product_list.html', {
        'manufacturer' : manufacturer,
        'product_list': product_list,
        'manufacturers': Manufacturer.objects.all(),
        'no_manufacturer_product_count': Product.objects.filter(manufacturer=None).count
    })

def tag_page(request, slug):
    tag = Tag.objects.get(slug=slug)
    product_list = tag.product_set.all()
    return render(request, 'shop/product_list.html', {
        'tag' : tag,
        'product_list' : product_list,
        'categories': Category.objects.all(),
        'no_category_product_count': Product.objects.filter(category=None).count
    })

shop/templates/shop/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block head_title %}Shop{% endblock %}</title>
  <link href="{% static 'shop/bootstrap4/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" media="screen"></link>
  <script src="https://kit.fontawesome.com/54c8fd0744.js" crossorigin="anonymous"></script>
</head>
<body>
  {% include 'shop/navbar.html' %}

   <div class="container">
    <div class="row">
      <div class="col-md-8 col-lg-9" id="main-area">
        {% block main_area %}
        {% endblock %}
      </div>
      <div class="col-md-4 col-lg-3">
        {% include 'shop/sidebar.html' %}
      </div>
    </div>
  </div>

  {% include 'shop/footer.html' %}

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
</body>
</html>

shop/templates/shop/comment_form.html
{% extends 'shop/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    Edit Comment - Shop
{% endblock %}

{% block main_area %}
    <h1>Edit Comment</h1>'
    <hr/>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
            {{form | crispy}}
        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>
{% endblock %}

shop/templates/shop/footer.html
  <!-- Footer-->
  <footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">서울 도봉구 삼양로144길 33 | 고객센터 02-901-1234 </p>
    </div>
  </footer>

shop/templates/shop/navbar.html
{% load socialaccount %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="/">ShoppingMall</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/shop/">Shop</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/about_company/">About Company</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav_item">
          <a class="nav-link" href="/mypage/">MY 페이지</a>
        </li>
        {% endif %}
      </ul>

      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {% if user.socialaccount_set.all.0.get_avatar_url %}
              <img class="rounded-circle mr-3" src="{{ user.socialaccount_set.all.0.get_avatar_url }}" width="25px">
              {% else %}
              <img class="rounded-circle mr-3" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" width="25px">
              {% endif %}
              {{user.username}}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="/accounts/logout/">LogOut</a>
            </div>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="#" data-toggle="modal" data-target="#loginModal">LogIn</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

<!-- Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><i class="fa-solid fa-right-to-bracket"></i> LogIn</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <div class="row">

          <div class="col-6">
            <a role="button" class="btn btn-outline-dark btn-block btn-sm"
               href="{% provider_login_url 'google' %}">
              <i class="fa-brands fa-google"></i> LogIn with Google</a>
            <a role="button" class="btn btn-outline-dark btn-block btn-sm"
                href="/accounts/login/">
              <i class="fa-regular fa-envelope"></i> LogIn with Email</a>
          </div>

          <div class="col-6">
            <a role="button" class="btn btn-outline-dark btn-block btn-sm"
                href="/accounts/signup/">
              <i class="fa-regular fa-envelope"></i> SignUp with Email</a>
          </div>

        </div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

shop/templates/shop/product_detail.html
{% extends 'shop/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
    {{product.name}} - Shop
{% endblock %}
{% block main_area %}

    <!-- Product content-->
    <div id="product-area" >
        <!-- Product header-->
        <header class="mb-4">
            <!-- Product title-->
            <h1 class="fw-bolder mb-1">{{product.name | lower}}</h1>
            {% if product.hook_text %}
            <h5 class="text-muted">{{product.hook_text}}</h5>
            {% endif %}
            <!-- Product meta content-->
            <div class="text-muted fst-italic mb-2">
                Registered on {{product.created_at | date:"Y-m-d h:m:s"}} by {{product.author|upper}}
            </div>
            <!-- Product categories-->
            {% if product.manufacturer %}
                <a class="badge bg-info text-decoration-none link-light" href="{{product.manufacturer.get_absolute_url}}">{{product.manufacturer}}</a>
            {% endif %}

            {% if product.category %}
                <a class="badge bg-warning text-decoration-none link-light" href="{{product.category.get_absolute_url}}">{{product.category}}</a>
            {% else %}
                <a class="badge bg-warning text-decoration-none link-light" href="/shop/category/no_category">미분류</a>
            {% endif %}
        </header>

        <!--게시물 수정-->
        {% if user.is_authenticated and user == product.author %}
            <a class="btn btn-info float-right" href="/shop/update_product/{{product.pk}}/" role="button">
                <i class="fas fa-pen">Edit Product</i>
            </a>
        {% endif %}

        <!-- Preview image figure-->
        <figure class="mb-4">
            <h5 class="fs-5 mb-4">가격: {{product.price}}메소</h5>
            {% if product.head_image %}
                <img class="img-fluid rounded" src="{{product.head_image.url}}" alt="{{product.name}}의 head_image" />
            {% else %}
                <img class="img-fluid rounded" src="https://picsum.photos/seed/{{product.pk}}/800/200" alt="random image" />
            {% endif %}
        </figure>

        <!-- Product content-->
        <section class="mb-5">
            <p class="fs-5 mb-4">가위 사용 가능 횟수: {{product.scissors}}회</p>
            <p class="fs-5 mb-4">{{product.content}}</p>
            {% if product.tags.exists %}
                <i class="fas fa-tag"></i>
                {% for t in product.tags.iterator %}
                <span class="badge badge-pill badge-light">
                    <a href="{{t.get_absolute_url}}">
                        {{t}}
                    </a>
                </span>
                {% endfor %}
            {% endif %}
            <br></br>
            {% if product.file_upload %}
            <a href="{{product.file_upload.url}}" class="btn btn-outline-dark" role="button" download>
                {% if product.get_file_ext == 'xlsx' or product.get_file_ext == 'xls' %}
                    <i class="fa-regular fa-file-excel"></i>
                {% elif product.get_file_ext == 'docx' or product.get_file_ext == 'doc' %}
                    <i class="fa-regular fa-file-word"></i>
                {% else %}
                    <i class="fa-regular fa-file"></i>
                {% endif %}
                Download {{product.get_file_name}}
            </a>
            {% endif %}
        </section>
    </div>

    <!-- Comments section-->
    <div id="comment-area" class="mb-5">
        <div class="card bg-light">
            <div class="card-body">
                <!-- Comment form-->
                    {% if user.is_authenticated %}
                        <form class="mb-4" id="comment-form" method="post" action="{{product.get_absolute_url}}new_comment/">
                            {% csrf_token %}
                            <div class="form-group">
                                {{comment_form | crispy}}
                            </div>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    {% else %}
                        <a role="button" class="btn btn-dark btn-block btn-sm" href="#"
                            data-toggle="modal" data-target="#loginModal">
                            Login and Leave a comment
                        </a>
                    {% endif %}

                {% if product.comment_set.exists %}
                    {% for comment in product.comment_set.iterator %}
                        <!-- Single comment-->
                        <div class="media d-flex" id="comment-{{comment.pk}}">
                            <img class="d-flex mr-3 rounded-circle" src="{{ comment.get_avatar_url }}" alt="{{comment.author}}" width="60px">
                            <div class="media-body ms-3">
                                {% if user.is_authenticated and comment.author == user %}
                                <div class="float-right">
                                    <a role="button" class="btn btn-sm btn-info float-right"
                                        href="/shop/update_comment/{{comment.pk}}">
                                        Edit</a>
                                    <a data-target="#deleteModal-{{comment.pk}}" data-toggle="modal" class="btn btn-sm btn-danger"
                                        href="#">
                                        Delete
                                    </a>
                                </div>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal-{{comment.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Are you Sure?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <del>{{comment |linebreaks}}</del>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <a role="button" class="btn btn-secondary"
             href="/shop/delete_comment/{{comment.pk}}">Delete</a>
        </div>
      </div>
    </div>
    </div>
                                {% endif %}

                                 <div class="fw-bold">
                                    {{comment.author.username}}
                                    <small class="text_muted">{{comment.created_at}}</small>
                                </div>
                                <p>{{comment.content | linebreaks}}</p>
                                {% if comment.created_at != comment.modified_at %}
                                    <p class="text-muted float-right">
                                        <small>Modified : {{comment.modified_at}}</small>
                                    </p>
                                {% endif%}
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

shop/templates/shop/product_form.html
{% extends 'shop/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    Register New Product - Shop
{% endblock %}

{% block main_area %}
    <h1>Create a New Product</h1>
    <hr/>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
            {{form | crispy}}
            <div id="div_id_tags_str">
                <label for="id_tags">Tags:</label>
                <input id="id_tags" type="text" name="tags_str" class="textinput textInput form-control">
            </div>
        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>
{% endblock %}

shop/templates/shop/product_list.html
{% extends 'shop/base.html' %}

{% block main_area %}
    {% if user.is_authenticated %}
        {% if user.is_superuser or user.is_staff %}
        <a class="btn btn-info float-right" href="/shop/create_product/" role="button">
            <i class="fas fa-pen"> New Product</i></a>
        {% endif %}
    {% endif %}

    <h2>Shop
        <!--사이드바 부분-->
        {% if search_info %}
            <span class="badge badge-secondary">{{search_info}}</span>
        {% endif %}
        {% if category %}
        - <span class="badge badge-secondary">{{category}}</span>
        {% endif %}
        {% if manufacturer %}
        - <span class="badge badge-secondary">{{manufacturer}}</span>
        {% endif %}
        {% if tag %}
        <i class="fas fa-tag"></i>
        - <span class="badge badge-secondary">
            {{tag}} {{tag.product_set.count}} </span>
        {% endif %}
    </h2>

    <!--물건 정렬-->
    {% if product_list.exists %}
    {% for p in product_list %}
    <div class="card mb-4" id="product-{{p.pk}}">
        {% if p.head_image %}
            <img class="card-img-top" style="height:200px" src="{{p.head_image.url}}" alt="{{p}}의 head_image" />
        {% else %}
        <img class="card-img-top" src="https://picsum.photos/seed/{{p.pk}}/800/200" alt="random image" />
        {% endif %}
        <div class="card-body">
            {% if p.category %}
            <span class="badge badge-warning float-right">
                <a href="{{p.category.get_absolute_url}}">{{p.category}}</a>
            </span>
            {% else %}
            <span class="badge badge-warning text-decorations-none float-right">
                <a href="/shop/category/no_category/">
                    미분류
                </a></span>
            {% endif %}

            {% if p.manufacturer %}
            <span class="badge badge-info float-right">
                <a href="{{p.manufacturer.get_absolute_url}}">{{p.manufacturer}}</a>
            </span>
            {% endif %}

            <h2 class="card-title">{{p.name | upper}}</h2>

            {% if p.hook_text %}
                <h6 class="text-muted"> {{p.hook_text}} </h6>
            {% endif %}
            <h5>가격: {{p.price | upper}}메소</h5>

            <!--태그 출력-->
            {% if p.tags.exists %}
                <i class="fas fa-tag"></i>
                {% for t in p.tags.iterator %}
                <span class="badge badge-pill badge-light">
                    <a href="{{t.get_absolute_url}}">
                        {{t}}
                    </a>
                </span>
                {% endfor %}
            {% endif %}
            <br>
            <a class="btn btn-primary" href="{{p.get_absolute_url}}">View Detail →</a>
        </div>

        <div class="card-footer">
            <div class="small text-muted">{{p.created_at| date:"Y-m-d h:m:s"}}</div>
            <a href="#">{{p.author | upper}}</a>
        </div>
    </div>
    {% endfor %}

    {% else %}
        <h5>아직 게시물이 없습니다.</h5>
    {% endif %}

    <!-- Pagination-->
    {% if is_paginated %}
    <nav aria-label="Pagination">
      <hr class="my-0" />
      <ul class="pagination justify-content-center my-4">
          {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}" tabindex="-1" aria-disabled="true">Newer</a></li>
          {% else %}
          <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">Newer</a></li>
          {% endif %}

          {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">Older</a></li>
          {% else %}
          <li class="page-item disabled"><a class="page-link" href="#!">Older</a></li>
          {% endif %}
      </ul>
    </nav>
    {% endif %}
{% endblock %}

shop/templates/shop/product_update_form.html
{% extends 'shop/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    Update Product info - Shop
{% endblock %}

{% block main_area %}
    <h1>Update Product</h1>
    <hr/>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
            {{form | crispy}}
            <div id="div_id_tags_str">
                <label for="id_tags">Tags:</label>
                <input id="id_tags" type="text" name="tags_str" value="{{tags_str_default}}" class="textinput textInput form-control">
            </div>
        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>
{% endblock %}